[build]
  command = "npm install -g typescript && npm ci && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[context.production]
  command = "npm install -g typescript && npm ci && npm run build"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview]
  command = "npm install -g typescript && npm ci && npm run build"
  
[dev]
  command = "npm run dev"
  port = 9999
  targetPort = 5173
  publish = "dist"
  framework = "#custom"
  autoLaunch = true

# Redirects for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers to improve security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://sheets.googleapis.com http://localhost:* https://hook.eu1.make.com; img-src 'self' data: https:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[functions]
  node_bundler = "esbuild" 